name: Build APK
description: Builds debug and release APKs
inputs:
  cache-encryption-key:
    description: 'Encryption key for the configuration cache'
    required: false
  sign-release:
    description: 'Whether to configure signing for a release build'
    required: true
    default: 'false'
  keystore-base64:
    description: 'Base64 encoded keystore for signing'
    required: false
  sign-base64:
    description: 'Base64 encoded signing configuration (sign.json)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Custom gradle setup
      uses: ./.github/actions/gradle-setup
      with:
        cache-encryption-key: ${{ inputs.cache-encryption-key || '' }}
    - name: Decode signing keystore
      if: inputs.sign-release == 'true'
      shell: bash
      env:
        KEYSTORE_BASE64: ${{ inputs.keystore-base64 }}
      run: |
        echo "Decoding keystore..."
        if [ -z "$KEYSTORE_BASE64" ]; then
          echo "Error: KEYSTORE_BASE64 input is missing for signed release."
          exit 1
        fi
        echo $KEYSTORE_BASE64 | base64 -d > app/sign.keystore
    - name: Deserialize signing configuration
      if: inputs.sign-release == 'true'
      shell: bash
      env:
        SIGN_BASE64: ${{ inputs.sign-base64 }}
      run: |
        echo "Configuring signing key..."
        if [ -z "$SIGN_BASE64" ]; then
          echo "Error: SIGN_BASE64 input is missing for signed release."
          exit 1
        fi
        echo $SIGN_BASE64 | base64 -d > app/sign.json
    - name: Build debug key signed release APK
      if: inputs.sign-release == 'false'
      shell: bash
      run: ./gradlew assembleDebugKeySignedRelease
    - name: Build signed release APK
      if: inputs.sign-release == 'true'
      shell: bash
      run: ./gradlew assembleDefaultKeySignedRelease
    - name: Rename and move APK with git hash and date
      shell: bash
      run: |
        # Get short git hash and date
        GIT_HASH=$(git rev-parse --short HEAD)
        BUILD_DATE=$(date +'%Y%m%d')
        APK_NAME="delta-auto-${BUILD_DATE}-${GIT_HASH}.apk"
        ARTIFACT_NAME="delta-auto-${BUILD_DATE}-${GIT_HASH}"
        
        UNSIGNED_RELEASE_APK_PATH="app/build/outputs/apk/debugKeySigned/release/app-debugKeySigned-release.apk"
        SIGNED_RELEASE_APK_PATH="app/build/outputs/apk/defaultKeySigned/release/app-defaultKeySigned-release.apk"
        
        if [ -e "$UNSIGNED_RELEASE_APK_PATH" ]; then
          mv "$UNSIGNED_RELEASE_APK_PATH" "$APK_NAME"
          echo "APK_FILENAME=$APK_NAME" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
        fi
        if [ -e "$SIGNED_RELEASE_APK_PATH" ]; then
          mv "$SIGNED_RELEASE_APK_PATH" "$APK_NAME"
          echo "APK_FILENAME=$APK_NAME" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
        fi
    - name: Upload APK
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: delta-auto-apk
        path: delta-auto-*.apk
        retention-days: 7
        if-no-files-found: error
